import type { GameLevel } from './types'

export const GAME_LEVELS: GameLevel[] = [
  // 生活習慣
  {
    id: 'brush-teeth',
    category: 'habits',
    title: '刷牙時間',
    titleEn: 'Brush Teeth',
    description: '幫小熊把牙齒刷乾淨！',
    character: 'peep',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🦷',
    color: '#a8e6cf',
    locked: false,
  },
  {
    id: 'wash-hands',
    category: 'habits',
    title: '洗手步驟',
    titleEn: 'Wash Hands',
    description: '按照正確順序洗手！',
    character: 'peep',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🤲',
    color: '#a8e6cf',
    locked: false,
  },
  {
    id: 'get-dressed',
    category: 'habits',
    title: '穿衣服',
    titleEn: 'Get Dressed',
    description: '幫小熊穿上正確的衣服！',
    character: 'peep',
    difficulty: 2,
    minAge: 3,
    maxAge: 5,
    icon: '👕',
    color: '#a8e6cf',
    locked: false,
  },
  {
    id: 'tidy-toys',
    category: 'habits',
    title: '整理玩具',
    titleEn: 'Tidy Toys',
    description: '把玩具放到正確的地方！',
    character: 'peep',
    difficulty: 2,
    minAge: 3,
    maxAge: 5,
    icon: '🧸',
    color: '#a8e6cf',
    locked: false,
  },
  // 英文學習
  {
    id: 'alphabet',
    category: 'english',
    title: '認識字母',
    titleEn: 'ABC Letters',
    description: '點擊字母聽發音！',
    character: 'hoppy',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🔤',
    color: '#ffd3b6',
    locked: false,
  },
  {
    id: 'animals',
    category: 'english',
    title: '動物英文',
    titleEn: 'Animal Names',
    description: '配對動物和英文名字！',
    character: 'hoppy',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🐾',
    color: '#ffd3b6',
    locked: false,
  },
  {
    id: 'colors',
    category: 'english',
    title: '顏色英文',
    titleEn: 'Colors',
    description: '認識各種顏色的英文！',
    character: 'hoppy',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🌈',
    color: '#ffd3b6',
    locked: false,
  },
  {
    id: 'numbers',
    category: 'english',
    title: '數字英文',
    titleEn: 'Numbers',
    description: '數一數，學英文數字！',
    character: 'hoppy',
    difficulty: 2,
    minAge: 3,
    maxAge: 5,
    icon: '🔢',
    color: '#ffd3b6',
    locked: false,
  },
  // 認知訓練
  {
    id: 'shapes',
    category: 'cognitive',
    title: '形狀配對',
    titleEn: 'Shape Match',
    description: '找出相同的形狀！',
    character: 'luna',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🔷',
    color: '#d4a5f5',
    locked: false,
  },
  {
    id: 'color-match',
    category: 'cognitive',
    title: '顏色辨識',
    titleEn: 'Color Match',
    description: '找出相同顏色的物品！',
    character: 'luna',
    difficulty: 1,
    minAge: 2,
    maxAge: 5,
    icon: '🎨',
    color: '#d4a5f5',
    locked: false,
  },
  {
    id: 'size-sort',
    category: 'cognitive',
    title: '大小排序',
    titleEn: 'Size Sort',
    description: '把物品從小排到大！',
    character: 'luna',
    difficulty: 2,
    minAge: 3,
    maxAge: 5,
    icon: '📏',
    color: '#d4a5f5',
    locked: false,
  },
  {
    id: 'emotions',
    category: 'cognitive',
    title: '情緒認識',
    titleEn: 'Emotions',
    description: '認識各種表情和情緒！',
    character: 'luna',
    difficulty: 2,
    minAge: 3,
    maxAge: 5,
    icon: '😊',
    color: '#d4a5f5',
    locked: false,
  },
]

export const CATEGORY_INFO = {
  habits: {
    label: '生活習慣',
    labelEn: 'Daily Habits',
    color: '#a8e6cf',
    bg: 'from-emerald-200 to-green-300',
    character: '🐣',
    characterName: 'Peep',
    description: '培養好習慣，每天都健康！',
  },
  english: {
    label: '英文學習',
    labelEn: 'English Fun',
    color: '#ffd3b6',
    bg: 'from-orange-200 to-yellow-300',
    character: '🐸',
    characterName: 'Hoppy',
    description: '邊玩邊學英文，超簡單！',
  },
  cognitive: {
    label: '認知訓練',
    labelEn: 'Brain Games',
    color: '#d4a5f5',
    bg: 'from-purple-200 to-pink-300',
    character: '🦄',
    characterName: 'Luna',
    description: '動動腦，越玩越聰明！',
  },
}

export const BADGES = [
  { id: 'first-play', icon: '🌟', label: '初次出發', condition: '完成第一個關卡' },
  { id: 'brush-master', icon: '🦷', label: '刷牙達人', condition: '刷牙關卡3星' },
  { id: 'abc-hero', icon: '🔤', label: '字母英雄', condition: '字母關卡3星' },
  { id: 'shape-wizard', icon: '🔷', label: '形狀魔法師', condition: '形狀關卡3星' },
  { id: 'star-collector', icon: '⭐', label: '星星收集家', condition: '累積30顆星' },
  { id: 'week-streak', icon: '🔥', label: '連續7天', condition: '連續7天遊戲' },
  { id: 'all-habits', icon: '💪', label: '好習慣王', condition: '完成所有生活習慣關卡' },
  { id: 'english-star', icon: '🏆', label: '英文之星', condition: '完成所有英文關卡' },
]
